[build]
functions = "netlify/functions"
command = "echo 'Building site'"
publish = "."

[[redirects]]
from = "/*"
to = "/jansat1.html"
status = 200

[build.environment]
SUPABASE_URL = "https://your-supabase-url.supabase.co"
SUPABASE_KEY = "your-supabase-anon-key"

